### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by liberalterian** [AboldUSER/ERC20-Bonding-Curve-Token#2]
Hey, I happened to clone this and it had a lot of bugs. I fixed them then stored in my [repo's](https://github.com/alpinelines/bonding-governor) bold-bugfix branch. The master branch is a new bonding curve from this [repo](https://github.com/meTokens/bancor-zero-formula).

**Comment by AboldUSER** [comment]
Wow, thanks, I didn't even realize I had this repo public, an old practice project I didn't finish 😅 
Just curious how did you even come across this?
